In [2]:

!pip install requests
!pip install os
!pip install shutil

import requests
import os
import shutil
import time

Requirement already satisfied: requests in c:\users\ericr\anaconda3\lib\site-packages (2.28.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ericr\anaconda3\lib\site-packages (from requests) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ericr\anaconda3\lib\site-packages (from requests) (1.26.14)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\ericr\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ericr\anaconda3\lib\site-packages (from requests) (3.4)

ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os
ERROR: Could not find a version that satisfies the requirement shutil (from versions: none)
ERROR: No matching distribution found for shutil

In [28]:
years = list(range(1960, 2024))
years

[1960,
 1961,
 1962,
 1963,
 1964,
 1965,
 1966,
 1967,
 1968,
 1969,
 1970,
 1971,
 1972,
 1973,
 1974,
 1975,
 1976,
 1977,
 1978,
 1979,
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023]

In [82]:
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"

#for year in years:
for year in years:
    url = url_start.format(year)
    data = requests.get(url)
    time.sleep(18)
    with open("mvp/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)

In [12]:
from bs4 import BeautifulSoup

In [57]:
with open("mvp/1992.html", encoding="utf-8") as f:
    page = f.read()
    
soup = BeautifulSoup(page, 'html.parser')
soup.find('tr', class_="over_header").decompose()

In [58]:
mvp_table = soup.find_all(id="mvp")[0]

In [43]:
import pandas as pd

In [44]:
mvp_1960 = pd.read_html(str(mvp_table))[0]

In [47]:
mvp_1960.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Wilt Chamberlain,30,PHI,80.0,444.0,540,0.822,81,45.5,24.1,24.2,7.8,NaN,NaN,0.683,NaN,0.441,21.9,0.285
1,2,Nate Thurmond,25,SFW,15.0,170.0,540,0.315,65,42.5,18.7,21.3,2.6,NaN,NaN,0.437,NaN,0.629,7.2,0.125
2,3,Bill Russell,32,BOS,5.0,96.0,540,0.178,81,40.7,13.3,21.0,5.8,NaN,NaN,0.454,NaN,0.610,12.2,0.178
3,4,Oscar Robertson,28,CIN,3.0,93.0,540,0.172,79,43.9,30.5,6.2,10.7,NaN,NaN,0.493,NaN,0.873,17.4,0.241
4,5,Rick Barry,22,SFW,2.0,52.0,540,0.096,78,40.7,35.6,9.2,3.6,NaN,NaN,0.451,NaN,0.884,14.4,0.218

In [18]:
mvp_1991["Year"] = 1991

In [19]:
mvp_1991.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,37.0,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,37.1,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,37.7,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,37.3,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,40.3,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991

In [129]:
dfs = []
for year in years:

    with open("mvp/{}.html".format(year), encoding="utf-8") as f:
                page = f.read()
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="over_header").decompose()
    mvp_table = soup.find_all(id="mvp")[0]
    mvp_df = pd.read_html(str(mvp_table))[0]
    mvp_df["Year"] = year
    dfs.append(mvp_df)

In [89]:
dfs

[]

In [130]:
mvps = pd.concat(dfs)

mvps.tail()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                Rank             Player                Age                 Tm
0                  1      Jamaal Wilkes                 21                GSW
1                  2          John Drew                 20                ATL
2                  3       Scott Wedman                 22                KCO
3                  4       Leonard Gray                 23                SEA
4                  5     Mike Sojourner                 21                ATL

  Voting                        Unnamed: 8_level_0 Per Game  ...             \
   First Pts Won Pts Max  Share                  G       MP  ...   TRB  AST
0    7.6     7.6      18  0.422                 82     30.7  ...   8.2  2.2
1    5.1     5.1      18  0.283                 78     29.3  ...  10.7  1.8
2    3.8     3.8      18  0.211                 80     31.9  ...   6.1  1.6
3    1.2     1.2      18  0.067                 75     30.4  ...   6.4  2.2
4    0.3     0.3      18  0.017                 73     29.2  ...   8.8  1.3

            Shooting            Advanced         Year
   STL  BLK      FG% 3P%    FT%       WS  WS/48
0  1.3  0.3    0.442 NaN  0.734      5.1  0.097  1975
1  1.5  0.5    0.428 NaN  0.713      7.1  0.149  1975
2  1.0  0.3    0.465 NaN  0.818      4.8  0.091  1975
3  0.8  0.3    0.489 NaN  0.722      4.0  0.084  1975
4  0.5  0.8    0.488 NaN  0.651      4.7  0.106  1975

[5 rows x 21 columns]

In [131]:
mvps.to_csv("roys2.csv")

In [1]:
import pandas as pd

player_fname = pd.read_csv(list)
player_lname = pd.read_csv()
letter = player_name[0][:1]
letter
#f"https://www.basketball-reference.com/players/{letter}/{}{}01.html"
pd.Series(last_name).to_csv('listofnames.csv')

ValueError: Invalid file path or buffer object type: <class 'type'>

In [29]:
player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

for year in years:
    url = player_stats_url.format(year)
    
    data = requests.get(url)
    
    with open("player/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)

In [6]:
!pip install selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

Collecting selenium
  Downloading selenium-4.9.1-py3-none-any.whl (6.6 MB)
     ---------------------------------------- 6.6/6.6 MB 26.2 MB/s eta 0:00:00
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.10.2-py3-none-any.whl (17 kB)
Collecting trio~=0.17
  Downloading trio-0.22.0-py3-none-any.whl (384 kB)
     ---------------------------------------- 384.9/384.9 kB ? eta 0:00:00
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\ericr\anaconda3\lib\site-packages (from selenium) (1.26.14)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\ericr\anaconda3\lib\site-packages (from selenium) (2022.12.7)
Requirement already satisfied: attrs>=19.2.0 in c:\users\ericr\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sniffio in c:\users\ericr\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Collecting outcome
  Downloading outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
Collecting async-generator>=1.9
  Downloading async_generator-1.10-py3-none-any.whl (18 kB)
Requirement already satisfied: idna in c:\users\ericr\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Collecting exceptiongroup>=1.0.0rc9
  Downloading exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Requirement already satisfied: sortedcontainers in c:\users\ericr\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\ericr\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Collecting wsproto>=0.14
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\ericr\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\ericr\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Collecting h11<1,>=0.9.0
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ---------------------------------------- 58.3/58.3 kB ? eta 0:00:00
Installing collected packages: outcome, h11, exceptiongroup, async-generator, wsproto, trio, trio-websocket, selenium
Successfully installed async-generator-1.10 exceptiongroup-1.1.1 h11-0.14.0 outcome-1.2.0 selenium-4.9.1 trio-0.22.0 trio-websocket-0.10.2 wsproto-1.2.0

In [7]:
driver = webdriver.Chrome(
    executable_path="/Users/ericr/chromedriver_32/chromedriver"
    )

C:\Users\ericr\AppData\Local\Temp\ipykernel_2620\2497404269.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(

In [30]:
player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

for year in years:
    url = player_stats_url.format(year)
    
    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(18)
    
    with open("player/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(driver.page_source)

In [31]:
from bs4 import BeautifulSoup

dfs = []
for year in years:
    with open("player/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    player_table = soup.find_all(id="per_game_stats")[0]
    player_df = pd.read_html(str(player_table))[0]
    player_df["Year"] = year
    dfs.append(player_df)

In [32]:
players = pd.concat(dfs)

In [33]:
players.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Gary Alcorn,C,23,DET,58,NaN,11.6,1.6,5.4,...,NaN,NaN,4.8,0.4,NaN,NaN,NaN,2.1,4.0,1960
1,2,Bob Anderegg,SF,22,NYK,33,NaN,11.3,1.7,4.3,...,NaN,NaN,2.1,0.9,NaN,NaN,NaN,1.0,4.0,1960
2,3,Paul Arizin*,SF,31,PHW,72,NaN,36.4,8.2,19.4,...,NaN,NaN,8.6,2.3,NaN,NaN,NaN,3.7,22.3,1960
3,4,Dick Barnett,SG,23,SYR,57,NaN,21.7,5.1,12.3,...,NaN,NaN,2.7,2.8,NaN,NaN,NaN,1.7,12.4,1960
4,5,Elgin Baylor*,SF,25,MNL,70,NaN,41.0,10.8,25.4,...,NaN,NaN,16.4,3.5,NaN,NaN,NaN,3.3,29.6,1960

In [36]:
players.dtypes

Rk        object
Player    object
Pos       object
Age       object
Tm        object
G         object
GS        object
MP        object
FG        object
FGA       object
FG%       object
3P        object
3PA       object
3P%       object
2P        object
2PA       object
2P%       object
eFG%      object
FT        object
FTA       object
FT%       object
ORB       object
DRB       object
TRB       object
AST       object
STL       object
BLK       object
TOV       object
PF        object
PTS       object
Year       int64
dtype: object

In [37]:
players.to_csv("players.csv")

In [38]:
players = pd.read_csv("players.csv")

In [39]:
del players["Unnamed: 0"]

In [40]:
del players["Rk"]

In [41]:
players["Player"] = players["Player"].str.replace("*","", regex=False)

In [42]:

players.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Gary Alcorn,C,23,DET,58,NaN,11.6,1.6,5.4,.292,...,NaN,NaN,4.8,0.4,NaN,NaN,NaN,2.1,4.0,1960
1,Bob Anderegg,SF,22,NYK,33,NaN,11.3,1.7,4.3,.385,...,NaN,NaN,2.1,0.9,NaN,NaN,NaN,1.0,4.0,1960
2,Paul Arizin,SF,31,PHW,72,NaN,36.4,8.2,19.4,.424,...,NaN,NaN,8.6,2.3,NaN,NaN,NaN,3.7,22.3,1960
3,Dick Barnett,SG,23,SYR,57,NaN,21.7,5.1,12.3,.412,...,NaN,NaN,2.7,2.8,NaN,NaN,NaN,1.7,12.4,1960
4,Elgin Baylor,SF,25,MNL,70,NaN,41.0,10.8,25.4,.424,...,NaN,NaN,16.4,3.5,NaN,NaN,NaN,3.3,29.6,1960

In [43]:
def single_team(df):
    if df.shape[0]==1:
        return df
    else:
        row = df[df["Tm"]=="TOT"]
        row["Tm"] = df.iloc[-1,:]["Tm"]
        return row

players = players.groupby(["Player", "Year"]).apply(single_team)

In [44]:
players

                                   Player Pos Age   Tm   G  GS    MP   FG  \
Player         Year
A.C. Green     1986 6798       A.C. Green  PF  22  LAL  82   1  18.8  2.5
               1987 7197       A.C. Green  PF  23  LAL  79  72  28.4  4.0
               1988 7599       A.C. Green  PF  24  LAL  82  64  32.1  3.9
               1989 8048       A.C. Green  PF  25  LAL  82  82  30.6  4.9
               1990 8510       A.C. Green  PF  26  LAL  82  82  33.0  4.7
...                                   ...  ..  ..  ...  ..  ..   ...  ...
Željko Rebrača 2002 14936  Željko Rebrača   C  29  DET  74   4  15.9  2.6
               2003 15436  Željko Rebrača   C  30  DET  30  12  16.3  2.7
               2004 16017  Željko Rebrača   C  31  ATL  24   2  11.4  1.4
               2005 16617  Željko Rebrača   C  32  LAC  58   2  16.0  2.3
               2006 17211  Željko Rebrača   C  33  LAC  29   2  14.2  1.8

                           FGA   FG%  ...  ORB  DRB  TRB  AST  STL  BLK  TOV  \
Player         Year                   ...
A.C. Green     1986 6798   4.7  .539  ...  2.0  2.7  4.6  0.7  0.6  0.6  1.2
               1987 7197   7.4  .538  ...  2.7  5.1  7.8  1.1  0.9  1.0  1.3
               1988 7599   7.8  .503  ...  3.0  5.7  8.7  1.1  1.1  0.5  1.5
               1989 8048   9.2  .529  ...  3.1  5.9  9.0  1.3  1.1  0.7  1.5
               1990 8510   9.8  .478  ...  3.2  5.5  8.7  1.1  0.8  0.6  1.4
...                        ...   ...  ...  ...  ...  ...  ...  ...  ...  ...
Željko Rebrača 2002 14936  5.1  .505  ...  1.1  2.8  3.9  0.5  0.4  1.0  1.1
               2003 15436  4.8  .552  ...  0.9  2.2  3.1  0.3  0.2  0.6  1.0
               2004 16017  3.2  .442  ...  1.0  1.5  2.4  0.3  0.2  0.5  0.7
               2005 16617  4.0  .568  ...  0.8  2.3  3.2  0.4  0.2  0.7  0.8
               2006 17211  3.3  .542  ...  0.4  1.8  2.2  0.3  0.2  0.7  0.8

                            PF   PTS  Year
Player         Year
A.C. Green     1986 6798   2.8   6.4  1986
               1987 7197   2.2  10.8  1987
               1988 7599   2.5  11.4  1988
               1989 8048   2.1  13.3  1989
               1990 8510   2.5  12.9  1990
...                        ...   ...   ...
Željko Rebrača 2002 14936  2.6   6.9  2002
               2003 15436  2.6   6.6  2003
               2004 16017  2.2   3.8  2004
               2005 16617  2.2   5.8  2005
               2006 17211  2.0   4.7  2006

[22351 rows x 30 columns]

In [45]:
players.index = players.index.droplevel()

In [46]:
players.index = players.index.droplevel()

In [47]:
players.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
6798,A.C. Green,PF,22,LAL,82,1,18.8,2.5,4.7,.539,...,2.0,2.7,4.6,0.7,0.6,0.6,1.2,2.8,6.4,1986
7197,A.C. Green,PF,23,LAL,79,72,28.4,4.0,7.4,.538,...,2.7,5.1,7.8,1.1,0.9,1.0,1.3,2.2,10.8,1987
7599,A.C. Green,PF,24,LAL,82,64,32.1,3.9,7.8,.503,...,3.0,5.7,8.7,1.1,1.1,0.5,1.5,2.5,11.4,1988
8048,A.C. Green,PF,25,LAL,82,82,30.6,4.9,9.2,.529,...,3.1,5.9,9.0,1.3,1.1,0.7,1.5,2.1,13.3,1989
8510,A.C. Green,PF,26,LAL,82,82,33.0,4.7,9.8,.478,...,3.2,5.5,8.7,1.1,0.8,0.6,1.4,2.5,12.9,1990

In [48]:
players.to_csv("players.csv")